/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as AuthRouteImport } from "./routes/_auth"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AuthWalletRouteImport } from "./routes/_auth/wallet"
import { Route as AuthSettingsRouteImport } from "./routes/_auth/settings"
import { Route as AuthJobsIndexRouteImport } from "./routes/_auth/jobs.index"
import { Route as AuthContractsIndexRouteImport } from "./routes/_auth/contracts.index"
import { Route as AuthJobsNewRouteImport } from "./routes/_auth/jobs.new"
import { Route as AuthJobsIdRouteImport } from "./routes/_auth/jobs.$id"
import { Route as AuthContractsNewRouteImport } from "./routes/_auth/contracts.new"
import { Route as AuthContractsIdRouteImport } from "./routes/_auth/contracts.$id"
import { Route as AuthJobsIdMatchesRouteImport } from "./routes/_auth/jobs_.$id.matches"

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWalletRoute = AuthWalletRouteImport.update({
  id: "/wallet",
  path: "/wallet",
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AuthRoute,
} as any)
const AuthJobsIndexRoute = AuthJobsIndexRouteImport.update({
  id: "/jobs/",
  path: "/jobs/",
  getParentRoute: () => AuthRoute,
} as any)
const AuthContractsIndexRoute = AuthContractsIndexRouteImport.update({
  id: "/contracts/",
  path: "/contracts/",
  getParentRoute: () => AuthRoute,
} as any)
const AuthJobsNewRoute = AuthJobsNewRouteImport.update({
  id: "/jobs/new",
  path: "/jobs/new",
  getParentRoute: () => AuthRoute,
} as any)
const AuthJobsIdRoute = AuthJobsIdRouteImport.update({
  id: "/jobs/$id",
  path: "/jobs/$id",
  getParentRoute: () => AuthRoute,
} as any)
const AuthContractsNewRoute = AuthContractsNewRouteImport.update({
  id: "/contracts/new",
  path: "/contracts/new",
  getParentRoute: () => AuthRoute,
} as any)
const AuthContractsIdRoute = AuthContractsIdRouteImport.update({
  id: "/contracts/$id",
  path: "/contracts/$id",
  getParentRoute: () => AuthRoute,
} as any)
const AuthJobsIdMatchesRoute = AuthJobsIdMatchesRouteImport.update({
  id: "/jobs_/$id/matches",
  path: "/jobs/$id/matches",
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/settings": typeof AuthSettingsRoute
  "/wallet": typeof AuthWalletRoute
  "/contracts/$id": typeof AuthContractsIdRoute
  "/contracts/new": typeof AuthContractsNewRoute
  "/jobs/$id": typeof AuthJobsIdRoute
  "/jobs/new": typeof AuthJobsNewRoute
  "/contracts/": typeof AuthContractsIndexRoute
  "/jobs/": typeof AuthJobsIndexRoute
  "/jobs/$id/matches": typeof AuthJobsIdMatchesRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/settings": typeof AuthSettingsRoute
  "/wallet": typeof AuthWalletRoute
  "/contracts/$id": typeof AuthContractsIdRoute
  "/contracts/new": typeof AuthContractsNewRoute
  "/jobs/$id": typeof AuthJobsIdRoute
  "/jobs/new": typeof AuthJobsNewRoute
  "/contracts": typeof AuthContractsIndexRoute
  "/jobs": typeof AuthJobsIndexRoute
  "/jobs/$id/matches": typeof AuthJobsIdMatchesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_auth": typeof AuthRouteWithChildren
  "/login": typeof LoginRoute
  "/_auth/settings": typeof AuthSettingsRoute
  "/_auth/wallet": typeof AuthWalletRoute
  "/_auth/contracts/$id": typeof AuthContractsIdRoute
  "/_auth/contracts/new": typeof AuthContractsNewRoute
  "/_auth/jobs/$id": typeof AuthJobsIdRoute
  "/_auth/jobs/new": typeof AuthJobsNewRoute
  "/_auth/contracts/": typeof AuthContractsIndexRoute
  "/_auth/jobs/": typeof AuthJobsIndexRoute
  "/_auth/jobs_/$id/matches": typeof AuthJobsIdMatchesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/settings"
    | "/wallet"
    | "/contracts/$id"
    | "/contracts/new"
    | "/jobs/$id"
    | "/jobs/new"
    | "/contracts/"
    | "/jobs/"
    | "/jobs/$id/matches"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/login"
    | "/settings"
    | "/wallet"
    | "/contracts/$id"
    | "/contracts/new"
    | "/jobs/$id"
    | "/jobs/new"
    | "/contracts"
    | "/jobs"
    | "/jobs/$id/matches"
  id:
    | "__root__"
    | "/"
    | "/_auth"
    | "/login"
    | "/_auth/settings"
    | "/_auth/wallet"
    | "/_auth/contracts/$id"
    | "/_auth/contracts/new"
    | "/_auth/jobs/$id"
    | "/_auth/jobs/new"
    | "/_auth/contracts/"
    | "/_auth/jobs/"
    | "/_auth/jobs_/$id/matches"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth": {
      id: "/_auth"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth/wallet": {
      id: "/_auth/wallet"
      path: "/wallet"
      fullPath: "/wallet"
      preLoaderRoute: typeof AuthWalletRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/settings": {
      id: "/_auth/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/jobs/": {
      id: "/_auth/jobs/"
      path: "/jobs"
      fullPath: "/jobs/"
      preLoaderRoute: typeof AuthJobsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/contracts/": {
      id: "/_auth/contracts/"
      path: "/contracts"
      fullPath: "/contracts/"
      preLoaderRoute: typeof AuthContractsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/jobs/new": {
      id: "/_auth/jobs/new"
      path: "/jobs/new"
      fullPath: "/jobs/new"
      preLoaderRoute: typeof AuthJobsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/jobs/$id": {
      id: "/_auth/jobs/$id"
      path: "/jobs/$id"
      fullPath: "/jobs/$id"
      preLoaderRoute: typeof AuthJobsIdRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/contracts/new": {
      id: "/_auth/contracts/new"
      path: "/contracts/new"
      fullPath: "/contracts/new"
      preLoaderRoute: typeof AuthContractsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/contracts/$id": {
      id: "/_auth/contracts/$id"
      path: "/contracts/$id"
      fullPath: "/contracts/$id"
      preLoaderRoute: typeof AuthContractsIdRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/jobs_/$id/matches": {
      id: "/_auth/jobs_/$id/matches"
      path: "/jobs/$id/matches"
      fullPath: "/jobs/$id/matches"
      preLoaderRoute: typeof AuthJobsIdMatchesRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthWalletRoute: typeof AuthWalletRoute
  AuthContractsIdRoute: typeof AuthContractsIdRoute
  AuthContractsNewRoute: typeof AuthContractsNewRoute
  AuthJobsIdRoute: typeof AuthJobsIdRoute
  AuthJobsNewRoute: typeof AuthJobsNewRoute
  AuthContractsIndexRoute: typeof AuthContractsIndexRoute
  AuthJobsIndexRoute: typeof AuthJobsIndexRoute
  AuthJobsIdMatchesRoute: typeof AuthJobsIdMatchesRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSettingsRoute: AuthSettingsRoute,
  AuthWalletRoute: AuthWalletRoute,
  AuthContractsIdRoute: AuthContractsIdRoute,
  AuthContractsNewRoute: AuthContractsNewRoute,
  AuthJobsIdRoute: AuthJobsIdRoute,
  AuthJobsNewRoute: AuthJobsNewRoute,
  AuthContractsIndexRoute: AuthContractsIndexRoute,
  AuthJobsIndexRoute: AuthJobsIndexRoute,
  AuthJobsIdMatchesRoute: AuthJobsIdMatchesRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
