/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as AuthRouteImport } from "./routes/_auth"
import { Route as AuthIndexRouteImport } from "./routes/_auth/index"
import { Route as AuthWalletsIndexRouteImport } from "./routes/_auth/wallets.index"
import { Route as AuthJobsIndexRouteImport } from "./routes/_auth/jobs.index"
import { Route as AuthContractsIndexRouteImport } from "./routes/_auth/contracts.index"

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthRoute,
} as any)
const AuthWalletsIndexRoute = AuthWalletsIndexRouteImport.update({
  id: "/wallets/",
  path: "/wallets/",
  getParentRoute: () => AuthRoute,
} as any)
const AuthJobsIndexRoute = AuthJobsIndexRouteImport.update({
  id: "/jobs/",
  path: "/jobs/",
  getParentRoute: () => AuthRoute,
} as any)
const AuthContractsIndexRoute = AuthContractsIndexRouteImport.update({
  id: "/contracts/",
  path: "/contracts/",
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof AuthIndexRoute
  "/login": typeof LoginRoute
  "/contracts/": typeof AuthContractsIndexRoute
  "/jobs/": typeof AuthJobsIndexRoute
  "/wallets/": typeof AuthWalletsIndexRoute
}
export interface FileRoutesByTo {
  "/login": typeof LoginRoute
  "/": typeof AuthIndexRoute
  "/contracts": typeof AuthContractsIndexRoute
  "/jobs": typeof AuthJobsIndexRoute
  "/wallets": typeof AuthWalletsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_auth": typeof AuthRouteWithChildren
  "/login": typeof LoginRoute
  "/_auth/": typeof AuthIndexRoute
  "/_auth/contracts/": typeof AuthContractsIndexRoute
  "/_auth/jobs/": typeof AuthJobsIndexRoute
  "/_auth/wallets/": typeof AuthWalletsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/login" | "/contracts/" | "/jobs/" | "/wallets/"
  fileRoutesByTo: FileRoutesByTo
  to: "/login" | "/" | "/contracts" | "/jobs" | "/wallets"
  id:
    | "__root__"
    | "/_auth"
    | "/login"
    | "/_auth/"
    | "/_auth/contracts/"
    | "/_auth/jobs/"
    | "/_auth/wallets/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth": {
      id: "/_auth"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth/": {
      id: "/_auth/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/wallets/": {
      id: "/_auth/wallets/"
      path: "/wallets"
      fullPath: "/wallets/"
      preLoaderRoute: typeof AuthWalletsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/jobs/": {
      id: "/_auth/jobs/"
      path: "/jobs"
      fullPath: "/jobs/"
      preLoaderRoute: typeof AuthJobsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/contracts/": {
      id: "/_auth/contracts/"
      path: "/contracts"
      fullPath: "/contracts/"
      preLoaderRoute: typeof AuthContractsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthContractsIndexRoute: typeof AuthContractsIndexRoute
  AuthJobsIndexRoute: typeof AuthJobsIndexRoute
  AuthWalletsIndexRoute: typeof AuthWalletsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthContractsIndexRoute: AuthContractsIndexRoute,
  AuthJobsIndexRoute: AuthJobsIndexRoute,
  AuthWalletsIndexRoute: AuthWalletsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
