/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as AuthRouteImport } from "./routes/_auth"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AuthWalletRouteImport } from "./routes/_auth/wallet"
import { Route as AuthMatchesRouteImport } from "./routes/_auth/matches"
import { Route as AuthContractsIndexRouteImport } from "./routes/_auth/contracts.index"
import { Route as AuthContractsIdRouteImport } from "./routes/_auth/contracts.$id"

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWalletRoute = AuthWalletRouteImport.update({
  id: "/wallet",
  path: "/wallet",
  getParentRoute: () => AuthRoute,
} as any)
const AuthMatchesRoute = AuthMatchesRouteImport.update({
  id: "/matches",
  path: "/matches",
  getParentRoute: () => AuthRoute,
} as any)
const AuthContractsIndexRoute = AuthContractsIndexRouteImport.update({
  id: "/contracts/",
  path: "/contracts/",
  getParentRoute: () => AuthRoute,
} as any)
const AuthContractsIdRoute = AuthContractsIdRouteImport.update({
  id: "/contracts/$id",
  path: "/contracts/$id",
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/matches": typeof AuthMatchesRoute
  "/wallet": typeof AuthWalletRoute
  "/contracts/$id": typeof AuthContractsIdRoute
  "/contracts/": typeof AuthContractsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/matches": typeof AuthMatchesRoute
  "/wallet": typeof AuthWalletRoute
  "/contracts/$id": typeof AuthContractsIdRoute
  "/contracts": typeof AuthContractsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_auth": typeof AuthRouteWithChildren
  "/login": typeof LoginRoute
  "/_auth/matches": typeof AuthMatchesRoute
  "/_auth/wallet": typeof AuthWalletRoute
  "/_auth/contracts/$id": typeof AuthContractsIdRoute
  "/_auth/contracts/": typeof AuthContractsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/matches"
    | "/wallet"
    | "/contracts/$id"
    | "/contracts/"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/login" | "/matches" | "/wallet" | "/contracts/$id" | "/contracts"
  id:
    | "__root__"
    | "/"
    | "/_auth"
    | "/login"
    | "/_auth/matches"
    | "/_auth/wallet"
    | "/_auth/contracts/$id"
    | "/_auth/contracts/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth": {
      id: "/_auth"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth/wallet": {
      id: "/_auth/wallet"
      path: "/wallet"
      fullPath: "/wallet"
      preLoaderRoute: typeof AuthWalletRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/matches": {
      id: "/_auth/matches"
      path: "/matches"
      fullPath: "/matches"
      preLoaderRoute: typeof AuthMatchesRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/contracts/": {
      id: "/_auth/contracts/"
      path: "/contracts"
      fullPath: "/contracts/"
      preLoaderRoute: typeof AuthContractsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/contracts/$id": {
      id: "/_auth/contracts/$id"
      path: "/contracts/$id"
      fullPath: "/contracts/$id"
      preLoaderRoute: typeof AuthContractsIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthMatchesRoute: typeof AuthMatchesRoute
  AuthWalletRoute: typeof AuthWalletRoute
  AuthContractsIdRoute: typeof AuthContractsIdRoute
  AuthContractsIndexRoute: typeof AuthContractsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthMatchesRoute: AuthMatchesRoute,
  AuthWalletRoute: AuthWalletRoute,
  AuthContractsIdRoute: AuthContractsIdRoute,
  AuthContractsIndexRoute: AuthContractsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
